In [890]:
import pandas as pd
import numpy as np

In [891]:
data = pd.read_csv("batting_stacked_hwh_fpos.csv")
data.head()

,Unnamed: 0,player_id,year-0,g-0,ab-0,r-0,h-0,double-0,triple-0,hr-0,...,1B,2B,3B,C,CF,DH,LF,P,RF,SS
0,0,ordazlu01,1997,12,22,3,6,1,0,0,...,0.000,0.351,0.050,0.000,0,0.000,0.00,0,0.000,0.599
1,1,schmimi01,1972,13,34,2,7,0,0,1,...,0.003,0.008,0.972,0.000,0,0.000,0.00,0,0.000,0.018
2,2,thomeji01,1991,27,98,7,25,4,2,1,...,0.000,0.000,0.996,0.000,0,0.004,0.00,0,0.000,0.000
3,3,diazma02,2003,4,9,2,1,0,0,0,...,0.008,0.000,0.000,0.000,0,0.000,0.94,0,0.053,0.000
4,4,taubeed01,1991,26,66,5,16,2,1,0,...,0.007,0.000,0.000,0.993,0,0.000,0.00,0,0.000,0.000

In [892]:
yvals = pd.read_csv("batting_yarr.csv")
yvals.head()
#unfortunately, we have more yvals than data points

   player_id    0    1    2    3    4    5    6    7    8    9
0  ordazlu01  0.0  0.0  0.0 -0.1  0.0  0.0  0.0  0.0  0.0  0.0
1  distebe01  0.0  0.0 -0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  schmimi01  6.2  7.9  8.8  7.7  7.4  6.8  7.0  5.0  6.1  6.1
3  thomeji01  5.5  3.3  4.5  4.7  5.6  7.4  4.7  3.2  0.2  4.9
4   diazma02  1.7  0.6 -0.9 -0.8 -0.1  0.0  0.0  0.0  0.0  0.0

In [893]:
yvals = pd.merge(yvals, data[["player_id"]], how="inner", left_on="player_id", right_on="player_id")
yvals.head()
#now, it's fixed

   player_id    0    1    2    3    4    5    6    7    8    9
0  ordazlu01  0.0  0.0  0.0 -0.1  0.0  0.0  0.0  0.0  0.0  0.0
1  schmimi01  6.2  7.9  8.8  7.7  7.4  6.8  7.0  5.0  6.1  6.1
2  thomeji01  5.5  3.3  4.5  4.7  5.6  7.4  4.7  3.2  0.2  4.9
3   diazma02  1.7  0.6 -0.9 -0.8 -0.1  0.0  0.0  0.0  0.0  0.0
4  taubeed01 -0.1  1.4  1.5 -1.2 -0.3  0.0  0.0  0.0  0.0  0.0

In [894]:
#just predict year 7 (0) for now
y = yvals["0"].as_matrix()
y

array([ 0. ,  7.9,  3.3, ...,  5.6,  2.5,  0.5])

In [895]:
for col in data.columns:
    print(col)

Unnamed: 0
player_id
year-0
g-0
ab-0
r-0
h-0
double-0
triple-0
hr-0
rbi-0
sb-0
cs-0
bb-0
so-0
ibb-0
hbp-0
sh-0
sf-0
g_idp-0
ob-0
pa-0
tb-0
war-0
ab_per_g-0
r_per_ab-0
batting_avg-0
double_per_ab-0
triple_per_ab-0
hr_per_ab-0
rbi_per_ab-0
sb_per_ob-0
cs_per_ob-0
sb_ratio-0
bb_per_pa-0
so_per_ab-0
slg-0
obp-0
rc-0
rc_per_ab-0
babip-0
iso-0
pa_per_so-0
year-1
g-1
ab-1
r-1
h-1
double-1
triple-1
hr-1
rbi-1
sb-1
cs-1
bb-1
so-1
ibb-1
hbp-1
sh-1
sf-1
g_idp-1
ob-1
pa-1
tb-1
war-1
ab_per_g-1
r_per_ab-1
batting_avg-1
double_per_ab-1
triple_per_ab-1
hr_per_ab-1
rbi_per_ab-1
sb_per_ob-1
cs_per_ob-1
sb_ratio-1
bb_per_pa-1
so_per_ab-1
slg-1
obp-1
rc-1
rc_per_ab-1
babip-1
iso-1
pa_per_so-1
year-2
g-2
ab-2
r-2
h-2
double-2
triple-2
hr-2
rbi-2
sb-2
cs-2
bb-2
so-2
ibb-2
hbp-2
sh-2
sf-2
g_idp-2
ob-2
pa-2
tb-2
war-2
ab_per_g-2
r_per_ab-2
batting_avg-2
double_per_ab-2
triple_per_ab-2
hr_per_ab-2
rbi_per_ab-2
sb_per_ob-2
cs_per_ob-2
sb_ratio-2
bb_per_pa-2
so_per_ab-2
slg-2
obp-2
rc-2
rc_per_ab-2
babip-2
iso-2
pa_per_so-2
year-3
g-3
ab-3
r-3
h-3
double-3
triple-3
hr-3
rbi-3
sb-3
cs-3
bb-3
so-3
ibb-3
hbp-3
sh-3
sf-3
g_idp-3
ob-3
pa-3
tb-3
war-3
ab_per_g-3
r_per_ab-3
batting_avg-3
double_per_ab-3
triple_per_ab-3
hr_per_ab-3
rbi_per_ab-3
sb_per_ob-3
cs_per_ob-3
sb_ratio-3
bb_per_pa-3
so_per_ab-3
slg-3
obp-3
rc-3
rc_per_ab-3
babip-3
iso-3
pa_per_so-3
year-4
g-4
ab-4
r-4
h-4
double-4
triple-4
hr-4
rbi-4
sb-4
cs-4
bb-4
so-4
ibb-4
hbp-4
sh-4
sf-4
g_idp-4
ob-4
pa-4
tb-4
war-4
ab_per_g-4
r_per_ab-4
batting_avg-4
double_per_ab-4
triple_per_ab-4
hr_per_ab-4
rbi_per_ab-4
sb_per_ob-4
cs_per_ob-4
sb_ratio-4
bb_per_pa-4
so_per_ab-4
slg-4
obp-4
rc-4
rc_per_ab-4
babip-4
iso-4
pa_per_so-4
year-5
g-5
ab-5
r-5
h-5
double-5
triple-5
hr-5
rbi-5
sb-5
cs-5
bb-5
so-5
ibb-5
hbp-5
sh-5
sf-5
g_idp-5
ob-5
pa-5
tb-5
war-5
ab_per_g-5
r_per_ab-5
batting_avg-5
double_per_ab-5
triple_per_ab-5
hr_per_ab-5
rbi_per_ab-5
sb_per_ob-5
cs_per_ob-5
sb_ratio-5
bb_per_pa-5
so_per_ab-5
slg-5
obp-5
rc-5
rc_per_ab-5
babip-5
iso-5
pa_per_so-5
 6th_year_age
weight
height
bats
throws
1B
2B
3B
C
CF
DH
LF
P
RF
SS

In [896]:
#remove things we obviously won't care about
for_rem = ["Unnamed: 0", "triple_per_ab-0", "triple-0", "cs-0", "ibb-0", "hbp-0", "sh-0", "sf-0", "g_idp-0", "ab_per_g-0", "r_per_ab-0", "double_per_ab-0", "cs_per_ob-0",
          "triple_per_ab-1", "triple-1", "cs-1", "ibb-1", "hbp-1", "sh-1", "sf-1", "g_idp-1", "ab_per_g-1", "r_per_ab-1", "double_per_ab-1", "cs_per_ob-1",
          "triple_per_ab-2", "triple-2", "cs-2", "ibb-2", "hbp-2", "sh-2", "sf-2", "g_idp-2", "ab_per_g-2", "r_per_ab-2", "double_per_ab-2", "cs_per_ob-2",
          "triple_per_ab-3", "triple-3", "cs-3", "ibb-3", "hbp-3", "sh-3", "sf-3", "g_idp-3", "ab_per_g-3", "r_per_ab-3", "double_per_ab-3", "cs_per_ob-3",
          "triple_per_ab-4", "triple-4", "cs-4", "ibb-4", "hbp-4", "sh-4", "sf-4", "g_idp-4", "ab_per_g-4", "r_per_ab-4", "double_per_ab-4", "cs_per_ob-4",
          "triple_per_ab-5", "triple-5", "cs-5", "ibb-5", "hbp-5", "sh-5", "sf-5", "g_idp-5", "ab_per_g-5", "r_per_ab-5", "double_per_ab-5", "cs_per_ob-5"]

data = data.drop(for_rem, axis = 1)

In [897]:
#things we probably don't care about.......but keep them in a separate category

for_rem2 = ["g-0", "rbi-0", "ob-0", "pa-0", "rbi_per_ab-0",
            "g-1", "rbi-1", "ob-1", "pa-1", "rbi_per_ab-1",
            "g-2", "rbi-2", "ob-2", "pa-2", "rbi_per_ab-2",
            "g-3", "rbi-3", "ob-3", "pa-3", "rbi_per_ab-3",
            "g-4", "rbi-4", "ob-4", "pa-4", "rbi_per_ab-4",
            "g-5", "rbi-5", "ob-5", "pa-5", "rbi_per_ab-5"]

data = data.drop(for_rem2, axis = 1)

In [898]:
#preliminary list of what we DO CARE ABOUT

#care = ["player_id", "year-0", "ab-3", "war-3", "babip-3", "so_per_ab-3",
#          "ab-4", "war-4", "babip-4", "so_per_ab-4",
#          "ab-5", "war-5", "babip-5", "so_per_ab-5",
#          " 6th_year_age", "weight", "height", "bats", "1B", "2B", "3B", "C", "CF", "DH", "LF", "RF", "SS"]

#war = ["war-0", "war-1", "war-2", "war-3", "war-4", "war-5"]

#data = data[care]
data = data.drop("throws", axis = 1)
#data = data.drop(war, axis = 1)

In [899]:
data

,player_id,year-0,ab-0,r-0,h-0,double-0,hr-0,sb-0,bb-0,so-0,...,1B,2B,3B,C,CF,DH,LF,P,RF,SS
0,ordazlu01,1997,22,3,6,1,0,3,1,2,...,0.000,0.351,0.050,0.000,0.000,0.000,0.000,0,0.000,0.599
1,schmimi01,1972,34,2,7,0,1,0,5,15,...,0.003,0.008,0.972,0.000,0.000,0.000,0.000,0,0.000,0.018
2,thomeji01,1991,98,7,25,4,1,1,5,16,...,0.000,0.000,0.996,0.000,0.000,0.004,0.000,0,0.000,0.000
3,diazma02,2003,9,2,1,0,0,0,1,3,...,0.008,0.000,0.000,0.000,0.000,0.000,0.940,0,0.053,0.000
4,taubeed01,1991,66,5,16,2,0,0,5,16,...,0.007,0.000,0.000,0.993,0.000,0.000,0.000,0,0.000,0.000
5,wilkiri01,1991,203,21,45,9,6,3,19,56,...,0.019,0.000,0.000,0.981,0.000,0.000,0.000,0,0.000,0.000
6,jamesdi01,1983,20,1,2,0,0,1,2,2,...,0.018,0.000,0.000,0.000,0.383,0.059,0.319,0,0.221,0.000
7,harpete01,1980,54,3,10,2,0,2,6,5,...,0.000,0.000,0.000,0.000,0.013,0.000,0.752,0,0.236,0.000
8,dentbu01,1973,117,17,29,2,0,2,10,18,...,0.000,0.004,0.001,0.000,0.000,0.000,0.000,0,0.000,0.995
9,sakatle01,1977,154,13,25,2,2,1,9,22,...,0.000,0.684,0.000,0.000,0.000,0.003,0.000,0,0.000,0.313
10,flahejo01,1992,66,3,13,2,0,0,3,7,...,0.000,0.000,0.000,0.998,0.000,0.002,0.000,0,0.000,0.000
11,molinjo01,1999,19,3,5,1,0,0,2,4,...,0.024,0.000,0.000,0.976,0.000,0.000,0.000,0,0.000,0.000
12,wynnema01,1983,366,66,89,16,7,12,38,52,...,0.000,0.000,0.000,0.000,0.877,0.000,0.101,0,0.022,0.000
13,hatchmi01,1979,93,9,25,4,1,1,7,12,...,0.059,0.000,0.084,0.000,0.168,0.203,0.281,0,0.205,0.000
14,allenga01,1979,241,27,49,10,3,1,20,42,...,0.000,0.000,0.020,0.965,0.000,0.015,0.000,0,0.000,0.000
15,maciajo01,1999,4,2,1,0,1,0,0,1,...,0.000,0.212,0.394,0.000,0.216,0.000,0.109,0,0.059,0.010
16,michaja01,2001,6,0,1,0,0,0,0,2,...,0.000,0.000,0.003,0.000,0.351,0.000,0.529,0,0.117,0.000
17,gallemi01,1985,77,13,16,5,1,1,12,14,...,0.000,0.499,0.140,0.000,0.000,0.003,0.000,0,0.002,0.356
18,yeagest01,1972,106,18,29,0,4,0,16,26,...,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0,0.000,0.000
19,corpoca01,2009,1,1,1,0,0,0,0,0,...,0.005,0.000,0.000,0.995,0.000,0.000,0.000,0,0.000,0.000
20,rodrihe02,1992,146,11,32,7,3,0,8,30,...,0.181,0.000,0.000,0.000,0.000,0.000,0.655,0,0.164,0.000
21,footeba01,1973,6,0,4,0,0,0,0,0,...,0.002,0.000,0.004,0.994,0.000,0.000,0.000,0,0.000,0.000
22,gilesbr02,1995,9,6,5,0,1,0,0,1,...,0.000,0.000,0.000,0.000,0.345,0.068,0.412,0,0.175,0.000
23,nahorbi01,1976,5,0,1,1,0,0,0,0,...,0.025,0.000,0.000,0.958,0.000,0.017,0.000,0,0.000,0.000
24,dernibo01,1980,7,5,4,0,0,3,1,0,...,0.000,0.000,0.000,0.000,0.792,0.000,0.024,0,0.185,0.000
25,mccanbr01,2005,180,20,50,7,5,1,18,26,...,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0,0.000,0.000
26,flannti01,1979,65,2,10,0,0,0,4,5,...,0.000,0.603,0.336,0.000,0.000,0.000,0.000,0,0.000,0.061
27,johnsti01,1973,465,39,99,10,0,6,29,93,...,0.006,0.338,0.070,0.000,0.000,0.017,0.004,0,0.000,0.564
28,seitzke01,1986,96,16,31,4,2,0,19,14,...,0.065,0.013,0.891,0.000,0.001,0.007,0.015,0,0.000,0.008
29,tagucso01,2002,15,4,6,0,0,1,2,1,...,0.000,0.005,0.000,0.000,0.391,0.000,0.408,0,0.196,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543,avilaal01,2009,61,9,17,4,5,0,10,18,...,0.002,0.000,0.002,0.997,0.000,0.000,0.000,0,0.000,0.000
1544,wilforo01,1977,171,22,42,1,1,10,17,26,...,0.000,0.954,0.009,0.000,0.016,0.012,0.004,0,0.002,0.004
1545,martica01,1983,89,8,23,3,6,0,4,19,...,0.247,0.000,0.003,0.000,0.000,0.000,0.734,0,0.017,0.000
1546,francbe01,2007,62,10,17,5,3,0,3,19,...,0.000,0.000,0.000,0.000,0.104,0.000,0.519,0,0.377,0.000
1547,gilbrro01,1972,38,2,9,1,0,1,2,10,...,0.000,0.862,0.132,0.000,0.000,0.000,0.000,0,0.000,0.006
1548,lavalmi01,1984,7,0,0,0,0,0,2,2,...,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0,0.000,0.000
1549,juraked01,1982,21,3,7,0,0,0,2,4,...,0.242,0.115,0.273,0.000,0.006,0.048,0.012,0,0.006,0.297
1550,pauljo01,1999,18,2,4,1,0,0,0,4,...,0.000,0.000,0.000,0.968,0.000,0.000,0.032,0,0.000,0.000
1551,esaskni01,1983,302,41,80,10,12,6,27,99,...,0.491,0.000,0.358,0.000,0.000,0.000,0.151,0,0.000,0.000
1552,caseyse01,1997,10,1,2,0,0,0,1,2,...,0.993,0.000,0.000,0.000,0.000,0.007,0.000,0,0.000,0.000
1553,suzukic01,2001,692,127,242,34,8,56,30,53,...,0.000,0.000,0.000,0.000,0.045,0.000,0.000,0,0.955,0.000
1554,wohlfji01,1972,25,3,6,1,0,0,2,6,...,0.000,0.019,0.000,0.000,0.013,0.053,0.674,0,0.242,0.000
1555,betanyu01,2005,211,24,54,11,1,1,11,24,...,0.000,0.011,0.000,0.000,0.000,0.000,0.000,0,0.000,0.989
1556,hardyjj01,2005,372,46,92,22,9,0,44,48,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,1.000
1557,crosbbo01,2003,12,1,0,0,0,0,1,5,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,1.000
1558,gaettga01,1981,26,4,5,0,2,0,0,6,...,0.001,0.001,0.965,0.000,0.000,0.005,0.016,0,0.000,0.011
1559,disarga01,1989,0,0,0,0,0,0,0,0,...,0.000,0.023,0.005,0.000,0.000,0.000,0.000,0,0.000,0.972
1560,eusebto01,1991,19,4,2,1,0,0,6,8,...,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0,0.000,0.000
1561,coninje01,1990,20,3,5,2,0,0,2,5,...,0.242,0.000,0.000,0.000,0.000,0.000,0.756,0,0.001,0.000
1562,schofdi02,1983,54,4,11,2,3,0,6,8,...,0.000,0.003,0.000,0.000,0.000,0.001,0.000,0,0.000,0.996
1563,brousbe01,2002,112,10,27,4,4,0,7,25,...,0.908,0.000,0.000,0.000,0.000,0.000,0.072,0,0.021,0.000
1564,humphte01,1971,26,1,5,1,0,0,0,4,...,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0,0.000,0.000
1565,fletcsc01,1981,46,6,10,4,0,0,2,4,...,0.000,0.165,0.127,0.000,0.000,0.007,0.000,0,0.000,0.701
1566,houstty01,1996,142,21,45,9,3,3,9,27,...,0.140,0.007,0.450,0.397,0.000,0.000,0.002,0,0.002,0.002
1567,oleartr01,1993,41,3,12,3,0,0,5,9,...,0.000,0.000,0.000,0.000,0.046,0.008,0.439,0,0.508,0.000
1568,slaugdo01,1982,115,14,32,6,3,0,9,12,...,0.000,0.000,0.000,0.983,0.000,0.017,0.000,0,0.000,0.000
1569,davismi02,1980,95,11,20,2,1,2,7,14,...,0.030,0.000,0.000,0.000,0.141,0.032,0.032,0,0.766,0.000
1570,muellbi02,1996,200,31,66,15,0,0,24,26,...,0.000,0.037,0.963,0.000,0.000,0.000,0.000,0,0.000,0.000
1571,steinte01,1986,15,3,5,0,2,0,1,0,...,0.051,0.000,0.036,0.814,0.000,0.075,0.011,0,0.013,0.000
1572,cummimi01,1993,36,5,4,1,0,0,4,9,...,0.000,0.000,0.000,0.000,0.414,0.128,0.203,0,0.256,0.000

In [900]:
data["decade"] = np.floor((data["year-0"] - 1970)/10)

data = data.drop("year-0", axis=1)
data.head()

,player_id,ab-0,r-0,h-0,double-0,hr-0,sb-0,bb-0,so-0,tb-0,...,2B,3B,C,CF,DH,LF,P,RF,SS,decade
0,ordazlu01,22,3,6,1,0,3,1,2,7,...,0.351,0.050,0.000,0,0.000,0.00,0,0.000,0.599,2
1,schmimi01,34,2,7,0,1,0,5,15,10,...,0.008,0.972,0.000,0,0.000,0.00,0,0.000,0.018,0
2,thomeji01,98,7,25,4,1,1,5,16,36,...,0.000,0.996,0.000,0,0.004,0.00,0,0.000,0.000,2
3,diazma02,9,2,1,0,0,0,1,3,1,...,0.000,0.000,0.000,0,0.000,0.94,0,0.053,0.000,3
4,taubeed01,66,5,16,2,0,0,5,16,20,...,0.000,0.000,0.993,0,0.000,0.00,0,0.000,0.000,2

In [901]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit(data["decade"])
binarized = lb.transform(data["decade"])
bins = pd.DataFrame(binarized)
bins.head()

   0  1  2  3
0  0  0  1  0
1  1  0  0  0
2  0  0  1  0
3  0  0  0  1
4  0  0  1  0

In [902]:
bins = bins.rename(columns = {0 : "1970s", 1 : "1980s", 2 : "1990s", 3 : "2000s"})
bins.head()

   1970s  1980s  1990s  2000s
0      0      0      1      0
1      1      0      0      0
2      0      0      1      0
3      0      0      0      1
4      0      0      1      0

In [903]:
data = pd.merge(data, bins, how="left", left_index=True, right_index=True)
data = data.drop("decade", axis = 1)
data.head()

,player_id,ab-0,r-0,h-0,double-0,hr-0,sb-0,bb-0,so-0,tb-0,...,CF,DH,LF,P,RF,SS,1970s,1980s,1990s,2000s
0,ordazlu01,22,3,6,1,0,3,1,2,7,...,0,0.000,0.00,0,0.000,0.599,0,0,1,0
1,schmimi01,34,2,7,0,1,0,5,15,10,...,0,0.000,0.00,0,0.000,0.018,1,0,0,0
2,thomeji01,98,7,25,4,1,1,5,16,36,...,0,0.004,0.00,0,0.000,0.000,0,0,1,0
3,diazma02,9,2,1,0,0,0,1,3,1,...,0,0.000,0.94,0,0.053,0.000,0,0,0,1
4,taubeed01,66,5,16,2,0,0,5,16,20,...,0,0.000,0.00,0,0.000,0.000,0,0,1,0

In [904]:
data = data.drop("player_id", axis = 1)
data.head()

,ab-0,r-0,h-0,double-0,hr-0,sb-0,bb-0,so-0,tb-0,war-0,...,CF,DH,LF,P,RF,SS,1970s,1980s,1990s,2000s
0,22,3,6,1,0,3,1,2,7,0.1,...,0,0.000,0.00,0,0.000,0.599,0,0,1,0
1,34,2,7,0,1,0,5,15,10,0.1,...,0,0.000,0.00,0,0.000,0.018,1,0,0,0
2,98,7,25,4,1,1,5,16,36,-0.1,...,0,0.004,0.00,0,0.000,0.000,0,0,1,0
3,9,2,1,0,0,0,1,3,1,-0.1,...,0,0.000,0.94,0,0.053,0.000,0,0,0,1
4,66,5,16,2,0,0,5,16,20,0.0,...,0,0.000,0.00,0,0.000,0.000,0,0,1,0

In [905]:
#still need to binarize handedness

lbh = LabelBinarizer()
lbh.fit(data["bats"])
binh = lbh.transform(data["bats"])
binh = pd.DataFrame(binh)
binh = binh.rename(columns = {0 : "S", 1 : "L", 2 : "R"})
binh.head()

   S  L  R
0  0  0  1
1  0  0  1
2  0  1  0
3  0  0  1
4  0  1  0

In [906]:
data = pd.merge(data, binh, how="left", left_index=True, right_index=True)
data = data.drop("bats", axis = 1)
data.head()

,ab-0,r-0,h-0,double-0,hr-0,sb-0,bb-0,so-0,tb-0,war-0,...,P,RF,SS,1970s,1980s,1990s,2000s,S,L,R
0,22,3,6,1,0,3,1,2,7,0.1,...,0,0.000,0.599,0,0,1,0,0,0,1
1,34,2,7,0,1,0,5,15,10,0.1,...,0,0.000,0.018,1,0,0,0,0,0,1
2,98,7,25,4,1,1,5,16,36,-0.1,...,0,0.000,0.000,0,0,1,0,0,1,0
3,9,2,1,0,0,0,1,3,1,-0.1,...,0,0.053,0.000,0,0,0,1,0,0,1
4,66,5,16,2,0,0,5,16,20,0.0,...,0,0.000,0.000,0,0,1,0,0,1,0

In [907]:
#Convert to matrix
X = data.as_matrix()
X[0:10]

array([[  22.,    3.,    6., ...,    0.,    0.,    1.],
       [  34.,    2.,    7., ...,    0.,    0.,    1.],
       [  98.,    7.,   25., ...,    0.,    1.,    0.],
       ...,
       [  54.,    3.,   10., ...,    0.,    0.,    1.],
       [ 117.,   17.,   29., ...,    0.,    0.,    1.],
       [ 154.,   13.,   25., ...,    0.,    0.,    1.]])

In [908]:
from sklearn.preprocessing import MinMaxScaler

Scaler = MinMaxScaler()
Scaler.fit(X)
X = Scaler.transform(X)
X[0:2]

array([[ 0.03179191,  0.02362205,  0.02479339,  0.0212766 ,  0.        ,
         0.02727273,  0.01030928,  0.01081081,  0.01944444,  0.02564103,
         0.27272727,  0.        ,  0.14285714,  1.        ,  0.04347826,
         0.09090909,  0.18181818,  0.30434783,  0.01482844,  0.07057341,
         0.3       ,  0.04545455,  0.21      ,  0.69230769,  0.21825963,
         0.07377049,  0.14761905,  0.10204082,  0.        ,  0.01869159,
         0.08695652,  0.08823529,  0.09863014,  0.01123596,  0.27015251,
         0.        ,  0.02272728,  1.        ,  0.14117648,  0.11764706,
         0.21176471,  0.34747475,  0.06696906,  0.09828571,  0.22962963,
         0.04357299,  0.15705128,  0.69230769,  0.01293103,  0.0212766 ,
         0.0044843 ,  0.        ,  0.        ,  0.00917431,  0.00819672,
         0.00896861,  0.00253807,  0.01020408,  0.11111111,  0.        ,
         0.05882353,  1.        ,  0.18181818,  0.22222222,  0.07407407,
         0.2       ,  0.00116873,  0.01333333,  0.14285714,  0.        ,
         0.12389381,  0.69230769,  0.14772727,  0.12318841,  0.08778626,
         0.03389831,  0.        ,  0.03076923,  0.04065041,  0.04739336,
         0.0617284 ,  0.00990099,  0.2948718 ,  0.        ,  0.00689655,
         0.66666667,  0.17094016,  0.09615385,  0.20032052,  0.34218289,
         0.03395053,  0.0785568 ,  0.2371134 ,  0.02403846,  0.28285714,
         0.69230769,  0.07943262,  0.05882353,  0.05833333,  0.05555556,
         0.        ,  0.        ,  0.02631579,  0.04020101,  0.04187192,
         0.04081633,  0.25      ,  0.        ,  0.        ,  0.69015782,
         0.0952381 ,  0.14285714,  0.25297619,  0.29508197,  0.02829361,
         0.08302212,  0.28571429,  0.06696429,  0.16139241,  0.69230769,
         0.1352518 ,  0.07857143,  0.09375   ,  0.03921569,  0.        ,
         0.02083333,  0.08759124,  0.06532663,  0.06216216,  0.01098901,
         0.44680852,  0.        ,  0.06060606,  0.4       ,  0.21621622,
         0.13829787,  0.18351064,  0.61682242,  0.0457286 ,  0.15198914,
         0.51219512,  0.0212766 ,  0.24668435,  0.21428571,  0.19354839,
         0.35714286,  0.        ,  0.351     ,  0.05      ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.599     ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [ 0.04913295,  0.01574803,  0.02892562,  0.        ,  0.02702703,
         0.        ,  0.05154639,  0.08108108,  0.02777778,  0.02564103,
         0.20588235,  0.11764704,  0.        ,  0.69015782,  0.125     ,
         0.44117647,  0.16806723,  0.325     ,  0.02141627,  0.06011083,
         0.33333333,  0.08823529,  0.032     ,  0.05128205,  0.5235378 ,
         0.35245902,  0.34285714,  0.2244898 ,  0.36734694,  0.07476636,
         0.44927536,  0.66666667,  0.37534247,  0.2247191 ,  0.26158039,
         0.19618528,  0.02739726,  0.8       ,  0.2780269 ,  0.37057221,
         0.3359673 ,  0.43137255,  0.30546066,  0.17242415,  0.24884793,
         0.23614896,  0.041431  ,  0.05128205,  0.81609195,  0.76595745,
         0.71748879,  0.50909091,  0.62068966,  0.21100917,  0.86885246,
         0.61883408,  0.78680203,  1.        ,  0.28169014,  0.19014084,
         0.00952776,  0.65714286,  0.30285714,  0.24295775,  0.36384977,
         0.39531479,  0.71493906,  0.12101307,  0.31077694,  0.26408451,
         0.12030268,  0.05128205,  0.79829545,  0.67391304,  0.53435115,
         0.57627119,  0.80851064,  0.22307692,  0.82113821,  0.85308057,
         0.72592593,  0.77227723,  0.33214709,  0.3380783 ,  0.00568627,
         0.70731707,  0.59064328,  0.3202847 ,  0.43594306,  0.48902196,
         0.56497059,  0.21491961,  0.29565217,  0.34252669,  0.07666667,
         0.05128205,  0.82836879,  0.82352941,  0.6375    ,  0.57407407,
         0.7755102 ,  0.12962963,  0.87719298,  0.74874372,  0.75369458,
         0.82653061,  0.2619863 ,  0.26027396,  0.02573529,  0.60869565,
         0.2805049 ,  0.25513699,  0.43664383,  0.37606838,  0.65377506,
         0.16547399,  0.28465347,  0.32748288,  0.09090137,  0.05128205,
         0.78273381,  0.81428571,  0.66517857,  0.52941176,  0.71698113,
         0.15625   ,  0.75912409,  0.61306533,  0.84324324,  0.97802198,
         0.54779412,  0.20955882,  0.05639098,  0.65217391,  0.3099851 ,
         0.22426471,  0.43014706,  0.78678678,  0.7779507 ,  0.42296812,
         0.5648855 ,  0.29963235,  0.14867157,  0.28571429,  0.35483871,
         0.57142857,  0.003     ,  0.008     ,  0.972     ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.018     ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ]])

In [909]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import GridSearchCV

alphas = [0.01, 0.1, 1, 10, 100]
nodes = [(6), (8), (10), (12), (14), (8, 3), (10, 3), (12, 4), (14, 5)]
params = {"alpha" : alphas, "hidden_layer_sizes" : nodes}

In [910]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, y, test_size = 0.25, random_state=12345)

In [911]:
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [998]:
from sklearn.linear_model import Ridge

#linear feature selector
from sklearn.feature_selection import RFE

Rge = Ridge(alpha = 2)

feat = 12

myRFE = RFE(Rge, n_features_to_select=feat, step = 1)

In [1000]:
myRFE.fit(Xtrain, Ytrain)

RFE(estimator=Ridge(alpha=2, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
  n_features_to_select=12, step=1, verbose=0)

In [1001]:
myRFE.ranking_

array([  9,  17,  74,  38,   8,  10,  75,  22,  85,  81,  51, 140,  77,
       109,  66,  76,  91,  19, 147,  24,  23,  18,  31,  80,  32,  33,
        99, 103,  57, 106,  42,  21, 102,  54, 122,  58,   1,  89, 114,
       128, 100,  59,  53, 132,   6,  67,  92,  90,  71,  14, 121,  70,
        15,  88, 112,  40, 131,  64, 143,  83, 113, 133, 134,  46,  97,
       119, 137,  98,  16,  45,  65,  62,  68,   2,  25,  69,   1,  55,
        26,  93,  73,   1,  44,  79, 144, 142, 110,  43, 101, 111, 138,
       129,  84, 149, 146, 105,  52,  11,  12,  34,   1,  56,  48,   1,
        72,   1,  60,   4,  29, 120,  47, 125, 145, 130,  13,  61,  30,
        39,  87,  27, 107,   1,  36,   1,  20,  96,  49, 127, 150,   1,
       115,  50,  63,  35,   1, 126,  86, 135,  37, 141, 136,   1,   7,
         1,   3,   5,  82, 124,  94,  95, 151,  78,  41, 152, 108, 123,
       116, 117, 118,  28, 104, 148, 139])

In [1002]:
colindex = np.argsort(myRFE.ranking_)[0:feat]
colindex

array([ 81,  76, 100, 103, 105, 121, 129, 123, 141, 143, 134,  36])

In [1003]:
best = list(data.columns[colindex])
best

['war-3',
 'hr-3',
 'hr-4',
 'so-4',
 'war-4',
 'r-5',
 'war-5',
 'double-5',
 'iso-5',
 ' 6th_year_age',
 'bb_per_pa-5',
 'sb_per_ob-1']

In [1004]:
from sklearn.metrics import r2_score

In [1005]:
Rdg2 = Ridge()
rdge_alp = {'alpha' : [0.01, 0.1, 1, 10, 100]}
GSrid = GridSearchCV(Rdg2, rdge_alp, return_train_score = True, scoring = 'r2')

In [1006]:
Xtrain_new = Xtrain[:, colindex]
Xtest_new = Xtest[:, colindex]
Xtest_new

array([[ 0.00990099,  0.34042553,  0.16326531, ...,  0.35714286,
         0.26229508,  0.        ],
       [ 0.02970297,  0.        ,  0.06122449, ...,  0.42857143,
         0.21234568,  0.        ],
       [ 0.0990099 ,  0.25531915,  0.20408163, ...,  0.35714286,
         0.16246498,  0.        ],
       ...,
       [ 0.04950495,  0.0212766 ,  0.06122449, ...,  0.5       ,
         0.2087912 ,  0.05263158],
       [ 0.00990099,  0.        ,  0.28571429, ...,  0.42857143,
         0.22790698,  0.02840909],
       [ 0.02970297,  0.0212766 ,  0.02040816, ...,  0.35714286,
         0.125     ,  0.03164847]])

In [1007]:
GSrid.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1008]:
GSrid.best_score_

0.40802125120529442

In [1009]:
GSrid.best_params_

{'alpha': 1}

In [1010]:
preds = GSrid.predict(Xtest_new)

r2_score(Ytest, preds)

0.47277310844019826

In [1011]:
alphas = [0.1, 1, 10, 100]
nodes = [(4), (6), (7), (8), (10), (8, 3), (10, 3), (12, 4), (14, 5)]
params = {"alpha" : alphas, "hidden_layer_sizes" : nodes}


MLP = MLPRegressor(activation = 'relu', solver = 'lbfgs', random_state = 54321)

GS = GridSearchCV(MLP, params, return_train_score = True, scoring = 'r2')

In [1012]:
GS.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=54321,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [0.1, 1, 10, 100], 'hidden_layer_sizes': [4, 6, 7, 8, 10, (8, 3), (10, 3), (12, 4), (14, 5)]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1013]:
GS.best_score_

0.40844721073773388

In [1014]:
GS.best_params_

{'alpha': 10, 'hidden_layer_sizes': 4}

In [1015]:
preds = GS.predict(Xtest_new)

r2_score(Ytest, preds)

0.4789674629386883

In [1016]:
from sklearn.tree import DecisionTreeRegressor

DTR = DecisionTreeRegressor()

mx_depth = [2, 3, 4, 5, 6, 7]
mn_lf_splt = [1, 2, 3, 4]
param_tree = {"max_depth" : mx_depth, "min_samples_leaf" : mn_lf_splt}
GStree = GridSearchCV(DTR, param_tree, return_train_score=True, scoring='r2')

In [1017]:
GStree.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'min_samples_leaf': [1, 2, 3, 4], 'max_depth': [2, 3, 4, 5, 6, 7]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1018]:
GStree.best_score_

0.30901666606255113

In [1019]:
GStree.best_params_

{'max_depth': 2, 'min_samples_leaf': 3}

In [1020]:
tree_preds = GStree.predict(Xtest_new)

r2_score(Ytest, tree_preds)

0.39475854986581316

In [1021]:
from sklearn.svm import SVR

svr = SVR(kernel = 'rbf')
Cval = [100, 500, 1000, 2000]
eps = [0.000001, 0.00001, 0.0001, 0.001]
gamma = [0.1, 0.01, 0.001, 0.0001]
svm_dict = {"C" : Cval, "epsilon" : eps, "gamma" : gamma}
GSsvm = GridSearchCV(svr, svm_dict, return_train_score = True, scoring = 'r2')

In [1022]:
GSsvm.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [100, 500, 1000, 2000], 'epsilon': [1e-06, 1e-05, 0.0001, 0.001], 'gamma': [0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1023]:
GSsvm.best_params_

{'C': 1000, 'epsilon': 1e-05, 'gamma': 0.001}

In [1024]:
GSsvm.best_score_

0.39565350187298148

In [1025]:
preds_svm = GSsvm.predict(Xtest_new)
r2_score(Ytest, preds_svm)

0.47185586527278744